Repository DIT112-V21/group-15, pull requests merged in 2021-04, with the labels that each got.

#13 Improvement-Basic-Movement
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  arduino/smartcar/smartcar.ino
Labels: enhancement, sprint#1

#14 Assignment 1
  arduino/smartcar/smartcar.ino
Labels: enhancement, sprint#1

#21 arduino-build-fixed
  .github/workflows/arduino-build.yml
  androidApp/.idea/vcs.xml
Labels: enhancement, sprint#2

#23 removed duplicate folder
  .idea/.gitignore
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/group-15.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  androidApp/.gitignore
  androidApp/.idea/.gitignore
  androidApp/.idea/.name
  androidApp/.idea/compiler.xml
  androidApp/.idea/gradle.xml
  androidApp/.idea/jarRepositories.xml
  androidApp/.idea/misc.xml
  androidApp/.idea/vcs.xml
  androidApp/app/.gitignore
  androidApp/app/build.gradle
  androidApp/app/proguard-rules.pro
  androidApp/app/src/androidTest/java/com/example/animamea/ExampleInstrumentedTest.kt
  androidApp/app/src/main/AndroidManifest.xml
  androidApp/app/src/main/java/com/example/animamea/FirstFragment.kt
  androidApp/app/src/main/java/com/example/animamea/MainActivity.kt
  androidApp/app/src/main/java/com/example/animamea/SecondFragment.kt
  androidApp/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  androidApp/app/src/main/res/drawable/ic_launcher_background.xml
  androidApp/app/src/main/res/font/poppins_medium.xml
  androidApp/app/src/main/res/layout/activity_main.xml
  androidApp/app/src/main/res/layout/content_main.xml
  androidApp/app/src/main/res/layout/fragment_first.xml
  androidApp/app/src/main/res/layout/fragment_second.xml
  androidApp/app/src/main/res/menu/menu_main.xml
  androidApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  androidApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  androidApp/app/src/main/res/mipmap-hdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  androidApp/app/src/main/res/mipmap-mdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  androidApp/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  androidApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  androidApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  androidApp/app/src/main/res/navigation/nav_graph.xml
  androidApp/app/src/main/res/values-night/themes.xml
  androidApp/app/src/main/res/values/colors.xml
  androidApp/app/src/main/res/values/dimens.xml
  androidApp/app/src/main/res/values/font_certs.xml
  androidApp/app/src/main/res/values/preloaded_fonts.xml
  androidApp/app/src/main/res/values/strings.xml
  androidApp/app/src/main/res/values/themes.xml
  androidApp/app/src/test/java/com/example/animamea/ExampleUnitTest.kt
  androidApp/build.gradle
  androidApp/gradle.properties
  androidApp/gradle/wrapper/gradle-wrapper.jar
  androidApp/gradle/wrapper/gradle-wrapper.properties
  androidApp/gradlew
  androidApp/gradlew.bat
  androidApp/settings.gradle
Labels: documentation

#27 update on obstacle avoidance
  arduino/smartcar/smartcar.ino
Labels: enhancement, sprint#2

#28 Code-Files-Fixed
  androidApp/.gitignore
  androidApp/.idea/.gitignore
  androidApp/.idea/.name
  androidApp/.idea/compiler.xml
  androidApp/.idea/gradle.xml
  androidApp/.idea/jarRepositories.xml
  androidApp/.idea/misc.xml
  androidApp/.idea/vcs.xml
  androidApp/app/.gitignore
  androidApp/app/build.gradle
  androidApp/app/proguard-rules.pro
  androidApp/app/src/androidTest/java/com/example/animamea/ExampleInstrumentedTest.kt
  androidApp/app/src/main/AndroidManifest.xml
  androidApp/app/src/main/java/com/example/animamea/FirstFragment.kt
  androidApp/app/src/main/java/com/example/animamea/MainActivity.kt
  androidApp/app/src/main/java/com/example/animamea/SecondFragment.kt
  androidApp/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  androidApp/app/src/main/res/drawable/ic_launcher_background.xml
  androidApp/app/src/main/res/font/poppins_medium.xml
  androidApp/app/src/main/res/layout/activity_main.xml
  androidApp/app/src/main/res/layout/content_main.xml
  androidApp/app/src/main/res/layout/fragment_first.xml
  androidApp/app/src/main/res/layout/fragment_second.xml
  androidApp/app/src/main/res/menu/menu_main.xml
  androidApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  androidApp/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  androidApp/app/src/main/res/mipmap-hdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  androidApp/app/src/main/res/mipmap-mdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  androidApp/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  androidApp/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  androidApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  androidApp/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  androidApp/app/src/main/res/navigation/nav_graph.xml
  androidApp/app/src/main/res/values-night/themes.xml
  androidApp/app/src/main/res/values/colors.xml
  androidApp/app/src/main/res/values/dimens.xml
  androidApp/app/src/main/res/values/font_certs.xml
  androidApp/app/src/main/res/values/preloaded_fonts.xml
  androidApp/app/src/main/res/values/strings.xml
  androidApp/app/src/main/res/values/themes.xml
  androidApp/app/src/test/java/com/example/animamea/ExampleUnitTest.kt
  androidApp/build.gradle
  androidApp/gradle.properties
  androidApp/gradle/wrapper/gradle-wrapper.jar
  androidApp/gradle/wrapper/gradle-wrapper.properties
  androidApp/gradlew
  androidApp/gradlew.bat
  androidApp/settings.gradle
Labels: duplicate

#29 MQTT connection in current Aurduino code
  ShadowApp/.idea/workspace.xml
  arduino/smartcar/smartcar.ino
Labels: enhancement, sprint#2

#32 Movement Improvement
  arduino/smartcar/smartcar.ino
Labels: bug, enhancement, sprint#2
